name: PHP CI

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Install Composer dependencies
        run: composer install --no-progress --no-suggest

      - name: Composer Autoload
        run: composer dump-autoload

      - name: Run PHPUnit Tests
        run: vendor/bin/phpunit --colors=always tests
